version: '3.8'

services:

  auction_nginx:
    image: nginx:stable-alpine
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - ./:/var/www/auction
#      - ./_docker/nginx/conf.d/nginx_local.conf:/etc/nginx/conf.d/default.conf
      - ./_docker/nginx/conf.d/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./_docker/certbot/conf:/etc/letsencrypt
      - ./_docker/certbot/www:/var/www/certbot
    depends_on:
      - auction_php
    networks:
        - app-network
    container_name: auction_nginx

  auction_php:
    build:
      context: ./_docker/php
      dockerfile: Dockerfile
    volumes:
      - ./:/var/www/auction
      - ./_docker/supervisor/conf.d:/etc/supervisor/conf.d
    networks:
      - app-network
    depends_on:
      - auction_mysql
    user: "1000:1000"
    container_name: auction_php

  auction_mysql:
    image: mysql:8.0
    restart: always
    volumes:
      - ./_docker/mysql:/var/lib/mysql
    environment:
        MYSQL_DATABASE: ${DOCKER_MYSQL_NAME}
        MYSQL_USER: ${DOCKER_MYSQL_USER}
        MYSQL_PASSWORD: ${DOCKER_MYSQL_PASSWORD}
        MYSQL_ROOT_PASSWORD: ${DOCKER_MYSQL_ROOT_PASSWORD}
    command: "mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci"
    networks:
        - app-network
    user: "1000:1000"
    container_name: auction_mysql

  auction_certbot:
    image: certbot/certbot
    volumes:
      - ./_docker/certbot/conf:/etc/letsencrypt
      - ./_docker/certbot/www:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
    networks:
      - app-network
    user: "1000:1000"
    container_name: auction_certbot

networks:
    app-network:
        driver: bridge
